{
 "title": "Environmental Control",
 "time": { "from": "2024-03-09T18:15:00.000Z", "to": "2024-03-09T18:44:45.000Z" },
 "panels": [
  {
   "title": "Actuation State",
   "type": "stat",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "sonder",
     "rawSql": "SELECT ac_state FROM sonder.environment_data ORDER BY date DESC LIMIT 1 "
    }
   ]
  },
  {
   "title": "Environment Temperature",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 4 },
   "targets": [
    {
     "dataset": "sonder",
     "rawSql": "SELECT temperature, ac_state, date FROM sonder.environment_data"
    }
   ]
  },
  {
   "title": "Temperature-Actuation",
   "type": "bargauge",
   "gridPos": { "h": 17, "w": 12, "x": 12, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "degree" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "sonder",
     "rawSql": "SELECT temperature, ac_state, date FROM sonder.environment_data ORDER BY date DESC "
    }
   ]
  },
  {
   "title": "State History",
   "type": "state-timeline",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 15 },
   "targets": [
    {
     "dataset": "sonder",
     "rawSql": "SELECT ac_state, date FROM sonder.environment_data"
    }
   ]
  }
 ]
}