{
 "title": "Machine Control",
 "time": { "from": "2024-03-09T18:15:02.355Z", "to": "2024-03-09T18:44:12.916Z" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Actuation State",
   "type": "stat",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "sonder",
     "rawSql": "SELECT ac_state, date FROM sonder.machine_data ORDER BY date DESC LIMIT 1 "
    }
   ]
  },
  {
   "title": "Temperature Humidity Timeseries",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 4 },
   "targets": [
    {
     "dataset": "sonder",
     "rawSql": "SELECT temperature, humidity, date, ac_state FROM sonder.machine_data"
    }
   ]
  },
  {
   "title": "Temperature Actuation",
   "type": "bargauge",
   "gridPos": { "h": 18, "w": 12, "x": 12, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "sonder",
     "rawSql": "SELECT temperature, ac_state FROM sonder.machine_data"
    }
   ]
  },
  {
   "title": "Actuation State Timeline",
   "type": "state-timeline",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "dataset": "sonder",
     "rawSql": "SELECT ac_state, date FROM sonder.machine_data"
    }
   ]
  }
 ]
}